print('hi hihih ihihi hihi ihihi ')
print('hi hihih ihihi hihi ihihi ')
print('hi hihih ihihi hihi ihihi ')
print('hi hihih ihihi hihi ihihi ')
print('hi hihih ihihi hihi ihihi ')
print ('fjsfsfdsjghsdgsdghugs')
print ('fjsfsfdsjghsdgsdghugs')
print ('fjsfsfdsjghsdgsdghugs')
print('utueruryiieyireiyiery')
print('znxzmnxmzxnzmxnmzxnzmxnzxnz')
print('asgdsfjsfhajsdjhsadhsajdsajkdh')
